---
- name: Ensure git is installed
  apt: pkg=git state=installed
  sudo: yes

- name: Ensure sabnzbdplus is installed
  apt: pkg=sabnzbdplus state=installed
  sudo: yes

- name: Upload sabnzbd default config file
  copy: src=sabnzbdplus dest=/etc/default/sabnzbdplus mode=0644
  sudo: yes

- name: Create .sabnzbd
  file: path=/home/aargh/.sabnzbd owner=aargh group=aargh state=directory

- name: Create .sabnzbd/scripts
  file: path=/home/aargh/.sabnzbd/scripts owner=aargh group=aargh state=directory

- name: Copy over the keygen script
  copy: src=keygen.sh dest=/home/aargh/.sabnzbd/keygen.sh
        owner=aargh group=aargh mode=0550

- name: Generate the random API key
  command: /home/aargh/.sabnzbd/keygen.sh apikey
  register: apikey
  sudo: yes
  sudo_user: aargh

- name: Generate the random NZB key
  command: /home/aargh/.sabnzbd/keygen.sh nzbkey
  register: nzbkey
  sudo: yes
  sudo_user: aargh

- name: Upload sabnzbd config file
  template: src=sabnzbd.ini dest=/home/aargh/.sabnzbd/sabnzbd.ini mode=0600 backup=yes owner=aargh group=aargh

- name: Ensure sabnzbd is started and enabled
  service: name=sabnzbdplus state=started enabled=yes
