---
- name: Ensure git is installed
  apt: pkg=git state=installed
  sudo: yes

- name: Ensure sabnzbdplus is installed
  apt: pkg=sabnzbdplus state=installed
  sudo: yes

- name: Upload sabnzbd default config file
  copy: src=sabnzbdplus dest=/etc/default/sabnzbdplus mode=0644
  sudo: yes

- name: Create .sabnzbd
  file: path=/home/aargh/.sabnzbd owner=aargh group=aargh state=directory

- name: Create .sabnzbd/scripts
  file: path=/home/aargh/.sabnzbd/scripts owner=aargh group=aargh state=directory

- name: Generate the random API key
  shell: (epoch=`date +%s`; rand=`od -An -N3 -i /dev/random`; m=$rand$epoch; echo $m | md5sum | cut -f 1 -d ' ' | tee /home/aargh/.sabnzbd/apikey) creates=/home/aargh/.sabnzbd/apikey
  register: apikey
  sudo: yes
  sudo_user: aargh

- name: Generate the random NZB key
  shell: (epoch=`date +%s`; rand=`od -An -N3 -i /dev/random`; m=$rand$epoch; echo $m | md5sum | cut -f 1 -d ' ' | tee /home/aargh/.sabnzbd/nzbkey) creates=/home/aargh/.sabnzbd/nzbkey
  register: nzbkey
  sudo: yes
  sudo_user: aargh

- name: Upload sabnzbd config file
  template: src=sabnzbd.ini dest=/home/aargh/.sabnzbd/sabnzbd.ini mode=0600 backup=yes owner=aargh group=aargh

- name: Start sabnzbd
  service: name=sabnzbdplus state=started enabled=yes
